# Generated by Django 2.2.26 on 2022-03-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jot.Category'),
        ),
    ]
