# Generated by Django 2.2.26 on 2022-03-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jot', '0002_auto_20220324_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(default='id352', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
