# Generated by Django 2.2.26 on 2022-03-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jot', '0003_auto_20220315_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jot.Users'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jot.Book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jot.Users'),
        ),
    ]
