# Generated by Django 2.2.26 on 2022-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jot', '0005_auto_20220318_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
